import fs from 'node:fs';
import {buildCabin} from '../public/js/cabin-model.js';
import {MATERIALS} from '../public/js/geometry.js';
const meshes=buildCabin(),binary=[],views=[],accessors=[],materials=[],nodes=[],gmeshes=[];let offset=0;
for(const item of meshes){const mat=MATERIALS[item.material],n=item.data.length/6,p=new Float32Array(n*3),no=new Float32Array(n*3);for(let i=0;i<n;i++){p.set(item.data.subarray(i*6,i*6+3),i*3);no.set(item.data.subarray(i*6+3,i*6+6),i*3);}let ids=[];for(let a of [p,no]){const buf=Buffer.from(a.buffer);views.push({buffer:0,byteOffset:offset,byteLength:buf.length,target:34962});binary.push(buf);offset+=buf.length;let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<a.length;i++) {min[i%3]=Math.min(min[i%3],a[i]);max[i%3]=Math.max(max[i%3],a[i]);}ids.push(accessors.length);accessors.push({bufferView:views.length-1,componentType:5126,count:n,type:'VEC3',min,max});}
 const material={name:item.material,pbrMetallicRoughness:{baseColorFactor:[...mat.color,1],metallicFactor:mat.metal,roughnessFactor:mat.rough},extras:{darbMaterial:mat}};
 if(item.material==='glass')material.extensions={KHR_materials_transmission:{transmissionFactor:.93},KHR_materials_volume:{thicknessFactor:.006,attenuationColor:[.87,.98,.94],attenuationDistance:12},KHR_materials_ior:{ior:1.45}};
 if(item.material==='orange'||item.material==='cabinRed')material.extensions={KHR_materials_clearcoat:{clearcoatFactor:.65,clearcoatRoughnessFactor:.22}};
 materials.push(material);gmeshes.push({name:item.material,primitives:[{attributes:{POSITION:ids[0],NORMAL:ids[1]},material:materials.length-1}]});nodes.push({mesh:gmeshes.length-1,name:'DARB_'+item.material});}
const gltf={asset:{version:'2.0',generator:'DARB original parametric cabin'},extensionsUsed:['KHR_materials_transmission','KHR_materials_volume','KHR_materials_ior','KHR_materials_clearcoat'],scene:0,scenes:[{nodes:nodes.map((_,i)=>i)}],nodes,meshes:gmeshes,materials,accessors,bufferViews:views,buffers:[{byteLength:offset}],extras:{provenance:'Original concept model; not an exact replica of any commercial cabin.',ropeAnchor:[-.12,2.7658,0],metresPerUnit:1}};
let json=Buffer.from(JSON.stringify(gltf));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const bin=Buffer.concat(binary),head=Buffer.alloc(12),jh=Buffer.alloc(8),bh=Buffer.alloc(8);head.writeUInt32LE(0x46546c67);head.writeUInt32LE(2,4);head.writeUInt32LE(12+8+json.length+8+bin.length,8);jh.writeUInt32LE(json.length);jh.writeUInt32LE(0x4e4f534a,4);bh.writeUInt32LE(bin.length);bh.writeUInt32LE(0x004e4942,4);fs.writeFileSync(new URL('../public/assets/models/darb-cabin.glb',import.meta.url),Buffer.concat([head,jh,json,bh,bin]));console.log('Original GLB created:',bin.length,'bytes;',meshes.reduce((n,m)=>n+m.data.length/18,0),'triangles');
